import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const DATA_DIR = path.join(__dirname, '..', 'server', 'data', 'hadith');
const OUTPUT_FILE = path.join(__dirname, '..', 'data', 'hadithStats.js');

const BOOKS_TO_PROCESS = [
  'bukhari', 'muslim', 'tirmidhi', 'abudawud', 'nasai', 'ibnmajah', 'malik',
  'ahmad', 'darimi', 'adab', 'bulugh', 'riyadussalihin', 'mishkat',
  'shamail', 'qudsi', 'nawawi', 'dehlawi'
];

function computeStats(data) {
  const metadata = data.metadata || {};
  const sectionsObj = metadata.sections || {};
  const hadiths = data.hadiths || [];

  const chapterCount = Object.keys(sectionsObj).length;
  
  // Get actual hadith numbers from the data
  const hadithNumbers = new Set();
  let min = Infinity, max = 0;
  
  for (const h of hadiths) {
    const num = h.number || h.heading?.number;
    if (num && typeof num === 'number') {
      hadithNumbers.add(num);
      if (num < min) min = num;
      if (num > max) max = num;
    }
  }
  
  // Also check in section headers for numbers
  for (const h of hadiths) {
    if (h.book && h.book.number) {
      hadithNumbers.add(h.book.number);
    }
    if (h.chapter && h.chapter.number) {
      const chapterNum = h.chapter.number;
      hadithNumbers.add(chapterNum);
    }
  }
  
  const canonicalCount = hadithNumbers.size;
  const totalRecords = hadiths.length;
  const chapterWiseCount = chapterCount;
  
  const decimalCount = Object.keys(sectionsObj).filter(k => k.includes('.')).length;
  
  let gapCount = 0;
  if (min !== Infinity && max > 0 && (max - min) < 10000) {
    for (let i = min; i <= max; i++) {
      if (!hadithNumbers.has(i)) gapCount++;
    }
  }

  const hasDiscrepancy = canonicalCount !== totalRecords && totalRecords > 0;

  return {
    totalChapters: chapterCount,
    totalRecords,
    canonicalCount: totalRecords,
    chapterWiseCount,
    decimalCount,
    gapCount,
    hasDiscrepancy
  };
}

async function processBook(bookId) {
  const engFile = path.join(DATA_DIR, bookId, `eng-${bookId}.json`);
  
  if (!fs.existsSync(engFile)) {
    console.log(`  ❌ No English file found for ${bookId}`);
    return null;
  }

  try {
    const content = fs.readFileSync(engFile, 'utf-8');
    const data = JSON.parse(content);
    const stats = computeStats(data);
    console.log(`  ✓ ${bookId}: ${stats.totalRecords} hadiths, ${stats.totalChapters} chapters`);
    return { bookId, stats };
  } catch (err) {
    console.log(`  ✗ Error processing ${bookId}: ${err.message}`);
    return null;
  }
}

async function main() {
  console.log('Generating hadith stats...\n');
  
  const results = {};
  
  for (const bookId of BOOKS_TO_PROCESS) {
    process.stdout.write(`Processing ${bookId}...`);
    const result = await processBook(bookId);
    if (result) {
      results[result.bookId] = result.stats;
    }
  }

  const output = `/**
 * Pre-computed Hadith Book Statistics
 * Generated by scripts/generateHadithStats.js
 * Do not edit manually
 */

export const HADITH_STATS = ${JSON.stringify(results, null, 2)};

export default HADITH_STATS;
`;

  fs.writeFileSync(OUTPUT_FILE, output, 'utf-8');
  
  console.log('\n\n✅ Stats saved to: ' + OUTPUT_FILE);
  console.log('📊 Total books processed:', Object.keys(results).length);
}

main();